name: 'Container image scan'
description: 'Scan container images for vulnerabilities and CIS guidelines'
inputs: 
  image-name:
    description: 'Docker image to scan'
    required: true
  severity-threshold:
    description: 'Minimum severities of vulnerabilities to be displayed (UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL)'
    required: false
    default: 'HIGH'
  username:
    description: 'Username to authenticate to the Docker registry'
    required: false
  password:
    description: 'Password to authenticate to the Docker registry'
    required: false
  token:
    description: 'Github token'
    default: ${{ github.token }}
  run-quality-checks:
    description: 'Add additional checks to ensure the image is secure and follows best practices and CIS standards'
    default: 'true'

outputs:
  scan-report-path:
    description: 'File name where the scan results are stored'

runs:
  using: 'node12'
  main: 'lib/main.js'